# Generated by Django 4.2.7 on 2026-06-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("local_manufacturer", "Local Manufacturer"),
                            ("importer", "Importer"),
                            ("distributor", "Distributor"),
                            ("agent", "Agent"),
                            ("international", "International Supplier"),
                        ],
                        default="distributor",
                        max_length=30,
                    ),
                ),
                (
                    "tin_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="TIN Number"
                    ),
                ),
                (
                    "business_license_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "efda_license_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="EFDA License Number"
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("alt_phone", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Ethiopia", max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        default=30, help_text="Payment terms in days"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("bank_name", models.CharField(blank=True, max_length=200)),
                ("bank_account_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["name"],
            },
        ),
    ]
