# Generated by Django 4.2.7 on 2026-06-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="MediWholesale Ethiopia", max_length=200),
                ),
                (
                    "short_name",
                    models.CharField(
                        default="MediWholesale",
                        help_text="Short name shown in sidebar",
                        max_length=50,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Medical Equipment & Medicine Wholesale System",
                        max_length=200,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Recommended: 200×60 px PNG with transparent background",
                        null=True,
                        upload_to="company/",
                    ),
                ),
                (
                    "logo_icon",
                    models.ImageField(
                        blank=True,
                        help_text="Square icon, 64×64 px",
                        null=True,
                        upload_to="company/",
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(default="Ethiopia", max_length=100)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "tin_number",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="TIN Number"
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="VAT Registration Number",
                    ),
                ),
                (
                    "business_license",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "regulatory_body",
                    models.CharField(
                        default="EFDA",
                        help_text="e.g. EFDA, FDA, WHO, MCA, NAFDAC",
                        max_length=100,
                    ),
                ),
                (
                    "regulatory_license",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="License number issued by regulatory body",
                        max_length=100,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="ETB",
                        help_text="ISO 4217 currency code, e.g. ETB, USD, EUR, KES",
                        max_length=10,
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        default="Br",
                        help_text="Symbol shown before amounts, e.g. Br, $, €, KSh",
                        max_length=10,
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="VAT percentage, e.g. 15 for 15%",
                        max_digits=5,
                    ),
                ),
                (
                    "vat_label",
                    models.CharField(
                        default="VAT",
                        help_text="e.g. VAT, GST, Sales Tax, TVA",
                        max_length=30,
                    ),
                ),
                (
                    "withholding_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Withholding tax %",
                        max_digits=5,
                    ),
                ),
                ("enable_vat", models.BooleanField(default=True)),
                (
                    "invoice_prefix",
                    models.CharField(
                        default="INV-", help_text="e.g. INV-, BILL-", max_length=20
                    ),
                ),
                (
                    "po_prefix",
                    models.CharField(
                        default="PO-", help_text="e.g. PO-, ORD-", max_length=20
                    ),
                ),
                (
                    "so_prefix",
                    models.CharField(
                        default="SO-", help_text="e.g. SO-, SLS-", max_length=20
                    ),
                ),
                ("credit_note_prefix", models.CharField(default="CN-", max_length=20)),
                (
                    "invoice_footer",
                    models.TextField(
                        blank=True, default="Thank you for your business."
                    ),
                ),
                (
                    "invoice_terms",
                    models.TextField(
                        blank=True,
                        default="Payment is due within the stated payment terms. Late payments may incur interest charges.",
                    ),
                ),
                ("default_payment_terms_days", models.PositiveIntegerField(default=30)),
                (
                    "expiry_alert_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Warn when items expire within this many days",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#006B3F",
                        help_text="Main brand color (hex)",
                        max_length=20,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#FCDD09", help_text="Accent color (hex)", max_length=20
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#EF2B2D",
                        help_text="Alert/danger color (hex)",
                        max_length=20,
                    ),
                ),
                (
                    "sidebar_dark",
                    models.BooleanField(
                        default=True, help_text="Use dark sidebar (recommended)"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("Africa/Addis_Ababa", "Africa/Addis Ababa (EAT)"),
                            ("Africa/Nairobi", "Africa/Nairobi (EAT)"),
                            ("Africa/Cairo", "Africa/Cairo"),
                            ("Africa/Lagos", "Africa/Lagos"),
                            ("Africa/Johannesburg", "Africa/Johannesburg"),
                            ("Europe/London", "Europe/London (GMT/BST)"),
                            ("Europe/Paris", "Europe/Paris (CET)"),
                            ("Asia/Dubai", "Asia/Dubai"),
                            ("Asia/Kolkata", "Asia/Kolkata (IST)"),
                            ("America/New_York", "America/New York (EST)"),
                            ("UTC", "UTC"),
                        ],
                        default="Africa/Addis_Ababa",
                        max_length=60,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("d/m/Y", "DD/MM/YYYY (e.g. 09/06/2026)"),
                            ("m/d/Y", "MM/DD/YYYY (e.g. 06/09/2026)"),
                            ("Y-m-d", "YYYY-MM-DD (e.g. 2026-06-09)"),
                            ("d-m-Y", "DD-MM-YYYY (e.g. 09-06-2026)"),
                            ("d M Y", "DD Mon YYYY (e.g. 09 Jun 2026)"),
                        ],
                        default="d/m/Y",
                        max_length=20,
                    ),
                ),
                ("language_code", models.CharField(default="en-us", max_length=10)),
                ("enable_cold_chain", models.BooleanField(default=True)),
                ("enable_controlled_substances", models.BooleanField(default=True)),
                ("enable_batch_tracking", models.BooleanField(default=True)),
                ("enable_multi_warehouse", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Settings",
                "verbose_name_plural": "Company Settings",
            },
        ),
    ]
