# Generated by Django 4.2.7 on 2026-06-20 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransfer",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktransferitem",
            name="quantity_requested",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("pending", "Pending"),
                    ("in_transit", "In Transit"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stocktransferitem",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfer_items",
                to="inventory.stockbatch",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransferitem",
            name="quantity_sent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
