# Generated by Django 4.2.7 on 2026-06-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0002_stocktransfer_approved_at_stocktransfer_approved_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransferitem",
            name="quantity_received",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="stocktransferitem",
            name="quantity_requested",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="stocktransferitem",
            name="quantity_sent",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
