# Generated by Django 4.2.7 on 2026-06-09 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("warehouse", "0001_initial"),
        ("inventory", "0001_initial"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="from_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements_out",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="to_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements_in",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_batches",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_batches",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_batches",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockbatch",
            unique_together={("product_variant", "warehouse", "batch_number")},
        ),
    ]
