# Generated by Django 4.2.7 on 2026-06-09 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("clinic", "Clinic"),
                            ("pharmacy", "Pharmacy"),
                            ("health_center", "Health Center"),
                            ("drug_store", "Drug Store"),
                            ("ngo", "NGO / Non-Profit"),
                            ("government", "Government Facility"),
                            ("private", "Private Individual"),
                        ],
                        default="pharmacy",
                        max_length=30,
                    ),
                ),
                (
                    "tin_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="TIN Number"
                    ),
                ),
                (
                    "business_license_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("license_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "efda_license_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="EFDA License Number"
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("alt_phone", models.CharField(blank=True, max_length=20)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("addis_ababa", "Addis Ababa"),
                            ("afar", "Afar"),
                            ("amhara", "Amhara"),
                            ("benishangul_gumuz", "Benishangul-Gumuz"),
                            ("dire_dawa", "Dire Dawa"),
                            ("gambela", "Gambela"),
                            ("harari", "Harari"),
                            ("oromia", "Oromia"),
                            ("sidama", "Sidama"),
                            ("snnpr", "SNNPR"),
                            ("somali", "Somali"),
                            ("tigray", "Tigray"),
                            ("sw_ethiopia", "South West Ethiopia"),
                        ],
                        max_length=30,
                    ),
                ),
                ("zone", models.CharField(blank=True, max_length=100)),
                ("woreda", models.CharField(blank=True, max_length=100)),
                ("kebele", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "credit_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Number of days for credit payment"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("business_license", "Business License"),
                            ("efda_license", "EFDA License"),
                            ("tin_certificate", "TIN Certificate"),
                            ("drug_retail_license", "Drug Retail License"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="customer_documents/")),
                ("description", models.CharField(blank=True, max_length=300)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Document",
                "verbose_name_plural": "Customer Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
