# Generated by Django 4.2.7 on 2026-06-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="markup_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Markup % applied to purchase price to set selling price on approval",
                max_digits=5,
                null=True,
            ),
        ),
    ]
