# Generated by Django 4.2.7 on 2026-06-09 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("brand", models.CharField(blank=True, max_length=200)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("piece", "Piece"),
                            ("box", "Box"),
                            ("carton", "Carton"),
                            ("pack", "Pack"),
                            ("bottle", "Bottle"),
                            ("tablet", "Tablet"),
                            ("vial", "Vial"),
                            ("ampoule", "Ampoule"),
                            ("liter", "Liter"),
                            ("ml", "Milliliter"),
                            ("kg", "Kilogram"),
                            ("gram", "Gram"),
                            ("unit", "Unit"),
                            ("set", "Set"),
                            ("pair", "Pair"),
                            ("roll", "Roll"),
                            ("sachet", "Sachet"),
                            ("tube", "Tube"),
                            ("strip", "Strip"),
                            ("inhaler", "Inhaler"),
                        ],
                        default="piece",
                        max_length=20,
                    ),
                ),
                (
                    "efda_registration_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="EFDA Registration Number",
                    ),
                ),
                ("is_controlled_substance", models.BooleanField(default=False)),
                ("requires_cold_chain", models.BooleanField(default=False)),
                ("reorder_level", models.PositiveIntegerField(default=10)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Weight in kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=100, unique=True)),
                ("barcode", models.CharField(blank=True, max_length=100)),
                ("size", models.CharField(blank=True, max_length=100)),
                ("packaging", models.CharField(blank=True, max_length=200)),
                (
                    "strength",
                    models.CharField(
                        blank=True,
                        help_text="For medicines: e.g. 500mg, 250mg/5ml",
                        max_length=100,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "min_selling_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_category",
                    models.CharField(
                        choices=[
                            ("vat_exempt", "VAT Exempt"),
                            ("taxable", "Taxable (15%)"),
                        ],
                        default="taxable",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "ordering": ["product__name", "strength"],
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generic_name", models.CharField(max_length=300)),
                ("brand_name", models.CharField(blank=True, max_length=300)),
                (
                    "dosage_form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("syrup", "Syrup"),
                            ("injection", "Injection"),
                            ("cream", "Cream"),
                            ("ointment", "Ointment"),
                            ("drops", "Drops"),
                            ("inhaler", "Inhaler"),
                            ("suppository", "Suppository"),
                            ("patch", "Patch"),
                            ("powder", "Powder"),
                            ("solution", "Solution"),
                            ("suspension", "Suspension"),
                            ("gel", "Gel"),
                            ("lotion", "Lotion"),
                            ("spray", "Spray"),
                            ("pessary", "Pessary"),
                            ("infusion", "Infusion"),
                            ("effervescent", "Effervescent Tablet"),
                            ("lozenge", "Lozenge"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("strength", models.CharField(blank=True, max_length=200)),
                (
                    "route_of_administration",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("injection_im", "Injection (IM)"),
                            ("injection_iv", "Injection (IV)"),
                            ("injection_sc", "Injection (SC)"),
                            ("topical", "Topical"),
                            ("inhalation", "Inhalation"),
                            ("ophthalmic", "Ophthalmic"),
                            ("otic", "Otic"),
                            ("rectal", "Rectal"),
                            ("vaginal", "Vaginal"),
                            ("sublingual", "Sublingual"),
                            ("transdermal", "Transdermal"),
                            ("nasal", "Nasal"),
                        ],
                        default="oral",
                        max_length=20,
                    ),
                ),
                ("therapeutic_category", models.CharField(blank=True, max_length=200)),
                ("pharmacological_class", models.CharField(blank=True, max_length=200)),
                ("prescription_required", models.BooleanField(default=False)),
                ("is_narcotic", models.BooleanField(default=False)),
                ("is_psychotropic", models.BooleanField(default=False)),
                (
                    "storage_condition",
                    models.CharField(
                        choices=[
                            ("room_temp", "Room Temperature (15-25°C)"),
                            ("cool", "Cool Place (8-15°C)"),
                            ("refrigerate", "Refrigerate (2-8°C)"),
                            ("freeze", "Freeze (-20°C or below)"),
                            ("protect_light", "Protect from Light"),
                            ("protect_moisture", "Protect from Moisture"),
                        ],
                        default="room_temp",
                        max_length=30,
                    ),
                ),
                ("shelf_life_months", models.PositiveIntegerField(default=24)),
                ("ethiopian_drug_code", models.CharField(blank=True, max_length=100)),
                (
                    "atc_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ATC Code"
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=300)),
                ("country_of_origin", models.CharField(blank=True, max_length=100)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_info",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine",
                "verbose_name_plural": "Medicines",
            },
        ),
    ]
